server:
  port: 8002
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: blog-oauth
          uri: lb://blog-oauth
          predicates:
            - Path=/blog-oauth/**
          filters:
            - StripPrefix=1
        - id: blog-admin
          uri: lb://blog-admin
          predicates:
            - Path=/blog-admin/**
          filters:
            - StripPrefix=1
        - id: blog-foreground
          uri: lb://blog-foreground
          predicates:
            - Path=/blog-foreground/**
          filters:
            - StripPrefix=1
        - id: blog-search
          uri: lb://blog-search
          predicates:
            - Path=/blog-search/**
          filters:
            - StripPrefix=1
        - id: blog-oam
          uri: lb://blog-oam
          predicates:
            - Path=/blog-oam/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8002/blog-oauth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password: adminroot
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/blog-oauth/oauth/token"
      - "/blog-oauth/rsa/publicKey"
      - "/blog-search/**"
      - "/blog-foreground/**"
      - "/blog-admin/admin/login"
      - "/blog-admin/admin/register"
      - "/blog-admin/minio/upload"

# - "/blog-foreground/sso/login"
  #      //- "/blog-foreground/sso/register"
  #      //- "/blog-foreground/sso/getAuthCode"
#开启SpringBoot Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always