server:
  port: 8005

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: adminroot  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
mybatis:
  mapper-locations:
  - classpath:dao/*.xml
  - classpath*:com/**/mapper/*.xml
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 自定义redis key
redis:
  database: blog
  key:
    loginUser: 'currentUser' #当前登录用户信息
  expire:
    authCode: 90 # 验证码超期时间
    common: 86400 # 24小时